### ISSUE TITLE
3.18 Compatibility

### ISSUE THREAD

**Issue by ghost** [jgke/gnome-extension-connman#2]
Hello,
Is it possible to add 3.18 compatibility?
Manually changing metadata.json and adding 3.18 does not seem to work...
Thanks, Adam.

**Comment by jgke** [comment]
Yes, there probably is just some method with a new name or something. I'll check it out soonish.

**Comment by ghost** [comment]
Thanks, appreciated.

**Comment by jgke** [comment]
Should be fixed in latest commit. I'm going to test it around a bit before pushing it to the Gnome extension repository.

**Comment by ghost** [comment]
Thanks for the quick solution, I'll try to have a look over the weekend.

Edit - Seems fine, looking forward to release.

**Comment by jgke** [comment]
Sent to the extension repo, it should be verified soonish.
